# Generated by Django 4.0.3 on 2022-05-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_fr', models.CharField(max_length=2000)),
                ('citation_en', models.CharField(max_length=2000)),
                ('auteur_fr', models.CharField(max_length=100)),
                ('auteur_en', models.CharField(max_length=100)),
            ],
        ),
    ]
