# Generated by Django 4.0.3 on 2022-05-22 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('année', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('nom_certif', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('fichier', models.CharField(max_length=120)),
                ('type_document', models.CharField(max_length=100)),
            ],
        ),
    ]
