# Generated by Django 4.0.3 on 2022-05-25 15:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_certification_balise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_année', models.CharField(max_length=30)),
                ('à_année', models.CharField(max_length=30)),
                ('entreprise', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('main_point_1', models.CharField(max_length=30)),
                ('main_point_2', models.CharField(max_length=30)),
                ('main_point_3', models.CharField(max_length=30)),
                ('main_point_4', models.CharField(max_length=30)),
                ('main_point_5', models.CharField(max_length=30)),
            ],
        ),
    ]
