# Generated by Django 4.0.3 on 2022-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='main_point_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_point_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_point_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_point_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_point_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
