# Generated by Django 4.0.3 on 2022-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_alter_experience_main_point_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='type_expérience',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
