# Generated by Django 4.0.3 on 2022-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_experience_type_expérience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='fichier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
