# Generated by Django 4.0.3 on 2022-05-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_experience_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='div_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
