# Generated by Django 4.0.3 on 2022-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poème',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poème', models.TextField()),
                ('titre', models.CharField(max_length=400)),
                ('recueil', models.CharField(max_length=400)),
                ('numéro', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
