# Generated by Django 4.0.3 on 2022-05-14 12:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poème',
            name='poème',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
